apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resumebuilder-appofapps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: resumebuilder
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ankuradarsh/Resume-Builder-ArgoCD.git
    path: 02-apps-cm
