replicaCount: 2

fullname: resumebuilder
image:
  repository: ankuradarsh/resume-builder
  tag: 58
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: NodePort
  port: 80
  nodePort: 30001

resources:
  limits:
   cpu: 100m
   memory: 256Mi
  requests:
   cpu: 60m
   memory: 128Mi
