apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: {{ .Values.fullname }}
  selector:
    app: {{ .Values.fullname }}